apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources.yaml
  # Namespace created by flicknote-deploy
  # Redpanda (Kafka-compatible) in flicknote-infra
  - headlamp.yaml
  - openmeter.yaml
  - grafana.yaml
  - gatus.yaml
